// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiWPywGyVEaKvg2sQyL66XD9k0PdOkyI',
    appId: '1:1038766897222:web:48d36bc3989059f3b73247',
    messagingSenderId: '1038766897222',
    projectId: 'quizapp-99965',
    authDomain: 'quizapp-99965.firebaseapp.com',
    storageBucket: 'quizapp-99965.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRHU42LKb6-K1-mH7NmX5z71vEw0jKKo',
    appId: '1:1038766897222:android:0b28a103faf2a406b73247',
    messagingSenderId: '1038766897222',
    projectId: 'quizapp-99965',
    storageBucket: 'quizapp-99965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQyUaeNpUhhdgf61o3kct24Fz7HrULrI',
    appId: '1:1038766897222:ios:d3673abd5a513769b73247',
    messagingSenderId: '1038766897222',
    projectId: 'quizapp-99965',
    storageBucket: 'quizapp-99965.appspot.com',
    iosClientId: '1038766897222-r3e30gjleu1sak769o72j8e6u4h4rklu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQyUaeNpUhhdgf61o3kct24Fz7HrULrI',
    appId: '1:1038766897222:ios:d04fd2a67b610d02b73247',
    messagingSenderId: '1038766897222',
    projectId: 'quizapp-99965',
    storageBucket: 'quizapp-99965.appspot.com',
    iosClientId: '1038766897222-mahbjc26l8t6a35mmeclg4sopc0avmqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
